# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Qn6Oo44whpWPjbAsCa9IDDLk0eMOsFP
"""

# DMW lab Inconsistent Data Handling
# 1] titanic dataset
# 2] own created dataframe ( using replace function for inconsistent data)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/titanic.csv")

df

df.info()

df.describe()

df.isnull().sum()

df.isna().sum()

df.duplicated().sum()

df.drop(["Cabin"],axis=1,inplace=True)

df

df.isna().sum()

df["Age"]=df["Age"].fillna(df["Age"].mean())

df.isna().sum()

df.duplicated().sum()

import pandas as pd
import numpy as np

simple_inconsistent_data = [
    {
        "ID": 1,
        "Name": "Alakh",
        "Gender": "Female",
        "Age": 28,
        "Salary": 75000,
        "City": "New York"
    },
    {
        "ID": 2,
        "Name": "boby ",
        "Gender": "Male",
        "Age": "35",
        "Salary": 60000,
        "City": "Los Angeles"
    },
    {
        "ID": 3,
        "Name": "Charu",
        "Gender": "M",
        "Age": None,
        "Salary": "80000",
        "City": "Chicago"
    },
    {
        "ID": 4,
        "Name": "Don",
        "Gender": "Female",
        "Age": 42,
        "Salary": -5000,
        "City": "Pune"
    },
    {
        "ID": 5,
        "Name": "eve",
        "Gender": "Other",
        "Age": 150,
        "Salary": None,
        "City": "Houston"
    }
]

df_inconsistent = pd.DataFrame(simple_inconsistent_data)

df_inconsistent

df_inconsistent["Gender"]=df_inconsistent["Gender"].replace({"Female":"F","Male":"M","Other":"F"})

df_inconsistent

df_inconsistent["Age"]=df_inconsistent["Age"].replace({None:25})
df_inconsistent["Salary"]=df_inconsistent["Salary"].replace({-5000:5000})

df_inconsistent

# Basic Scatter Plot
plt.figure(figsize=(8, 5))
sns.scatterplot(x='Age', y='Salary', data=df_inconsistent)
plt.title('Basic Scatter Plot of Age vs. Salary')
plt.xlabel('Age')
plt.ylabel('Salary')

plt.show()

# Scatter Plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age', y='Salary', data=df_inconsistent,
                hue='Gender',
                palette='coolwarm',
                s=100,
                alpha=0.7)
plt.title('Scatter Plot of Age vs. Salary by Gender')
plt.xlabel('Age')
plt.ylabel('Salary')
plt.legend(title='Gender')

plt.show()

# Box Plot of Salary by Gender
sns.boxplot(x='Gender', y='Salary', data=df_inconsistent,
            palette='Set2')
plt.title('Box Plot of Salary Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Salary')

plt.show()